"""empty message

Revision ID: fc7b86109eef
Revises: 
Create Date: 2020-05-04 11:36:00.825000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc7b86109eef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_authors', sa.Column('tel', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('t_authors', 'tel')
    # ### end Alembic commands ###
